# Generated by Django 3.1.3 on 2021-10-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_Descriptor', models.JSONField()),
                ('Model_Descriptor_vector', models.JSONField()),
                ('unused_links', models.JSONField()),
                ('Frames_Duration', models.JSONField()),
            ],
        ),
    ]
